title: TitanTurtles Cybersecurity Club
description: MISSION: CREATE AND ELEVATE AWARENESS AND KNOWLEDGE OF CYBERSECURITY FOR YOUTH, ORGANIZATIONS AND COMMUNITIES
description2: VISION: We are a diverse, connected and inspiring team partnering with school districtts, organizations and communities to deliver transformational knowledge sharing and value creation
description3: STRATEGY: Unleash the full potential of our students. Create social awareness of CyberSecurity through education, sharing and projects.

show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
